"""Files the update overwrites must say so, and only those.

run-append.sh overwrites every ff-*.cfg on each flash without asking, and
printer.base.cfg rides along with the software component, which a flash
replaces wholesale. That is only fair to the user if the file itself says so
before they edit it -- the alternative is a change that vanishes on the next
update with one line in a log nobody reads.

moonraker.conf is the counter-case and is checked from the other side: it is
KEPT when edited, because there is no include-and-override seam for it and a
printer reached through a tuned trusted_clients block would lose that access.
It must NOT carry the banner, or the banner starts lying.

Adding a config to either recipe's config directory therefore forces a
decision here, which is the point. There are two of them now -- the ff-*.cfg
are anvil-core's, printer.base.cfg is pkgs/klipper's -- and the `cfgdir`
fixture merges them the way the printer does.
"""
import os
import re

import pytest

BANNER = "DO NOT EDIT THIS FILE"
OVERRIDE_HINT = "printer.cfg"

# Overwritten wholesale on every update -- must warn.
#
# printer.chamber.cfg joined this list when it became a package of its own.
# It used to ride the software component to /usr/prog/klipper/config, where a
# flash replaces it wholesale and there is nothing for a user's edit to
# survive; now installer/run-append.sh overwrites it in /usr/data/config on
# the same terms as the ff-*.cfg, so it owes the same warning. The prefix
# matches the two model files under their merged names as well as the plain
# one a printer sees.
OWNED_PREFIXES = ("ff-", "printer.chamber.cfg")
OWNED_EXACT = ("printer.base.cfg",)

# Preserved when the user has edited it -- must not warn.
PRESERVED = ("moonraker.conf",)


def config_files(cfgdir):
    return sorted(f for f in os.listdir(cfgdir) if f.endswith((".cfg", ".conf")))


def owned(name):
    return name.startswith(OWNED_PREFIXES) or name in OWNED_EXACT


@pytest.fixture(scope="session")
def shipped(cfgdir):
    """What reaches the printer, by basename.

    Read from the recipes rather than a built tree so this needs no package:
    ff-*.cfg and moonraker.conf are anvil-core's, printer.base.cfg is
    pkgs/klipper's, and the cfgdir fixture is the one directory they land in.
    """
    return cfgdir, config_files(cfgdir)


def test_every_mod_owned_config_warns_the_user(shipped):
    cfgdir, names = shipped
    missing = []
    for name in names:
        if not owned(name):
            continue
        text = open(os.path.join(cfgdir, name), encoding="utf-8").read()
        if BANNER not in text:
            missing.append(name)
    assert not missing, (
        "these are overwritten on every update but do not say so: %s"
        % ", ".join(missing))


def test_the_warning_points_somewhere_useful(shipped):
    """A warning with no alternative is just a scolding."""
    cfgdir, names = shipped
    for name in names:
        if not owned(name):
            continue
        text = open(os.path.join(cfgdir, name), encoding="utf-8").read()
        head = text[:text.index(BANNER) + 2000]
        assert OVERRIDE_HINT in head, (
            "%s warns but never names printer.cfg as the place to put changes"
            % name)


def test_the_banner_is_at_the_top(shipped):
    """Past the first screenful it is not a warning, it is trivia."""
    cfgdir, names = shipped
    late = []
    for name in names:
        if not owned(name):
            continue
        lines = open(os.path.join(cfgdir, name), encoding="utf-8").read().splitlines()
        where = next(i for i, l in enumerate(lines) if BANNER in l)
        if where > 6:
            late.append("%s (line %d)" % (name, where + 1))
    assert not late, "banner buried too far down: %s" % ", ".join(late)


def test_preserved_configs_do_not_claim_to_be_overwritten(cfgdir):
    """moonraker.conf keeps the .mod-new dance, so it must not warn."""
    for name in PRESERVED:
        path = os.path.join(cfgdir, name)
        if os.path.isfile(path):
            text = open(path, encoding="utf-8").read()
            assert BANNER not in text, (
                "%s is kept when edited, so it must not carry the "
                "overwrite warning" % name)


def test_installer_actually_overwrites_what_the_banner_promises(root):
    """The banner is a claim about run-append.sh -- hold it to that.

    A banner that says "overwritten every update" while the installer still
    leaves a .mod-new is worse than no banner: the user trusts it, puts nothing
    in printer.cfg, and their edit quietly wins instead.
    """
    src = open(os.path.join(root, "installer", "run-append.sh"),
               encoding="utf-8").read()
    body = src[src.index("klipper + moonraker configs"):]
    # One case label carries every mod-owned name. Read it out of the script
    # rather than hard-coding it, so that adding a name to the branch and
    # forgetting to add it here cannot pass -- the check below is that the
    # label covers everything OWNED_PREFIXES claims is overwritten.
    # The case LABEL, not the paragraph of comment above it that also names
    # ff-*.cfg -- a plain index() finds the prose first and reads a "label"
    # that matches nothing.
    m = re.search(r"^[ \t]*(ff-\*\.cfg[^)\n]*)\)[ \t]*$", body, re.M)
    assert m, "run-append.sh has no case label for the mod-owned configs"
    start, label = m.start(), m.group(1)
    for pat in OWNED_PREFIXES:
        # printer.base.cfg is the exception the docstring names: it rides the
        # software component and a flash replaces it, so it is not here.
        want = pat + "*.cfg" if pat.endswith("-") else pat
        assert want in label, (
            "run-append.sh's overwrite branch does not match %s, but this "
            "module says files matching it are overwritten every update. "
            "Either add it to the branch or drop the banner from those files."
            % want)
    # The overwrite branch must not fall through to the .mod-new path.
    branch = body[start:]
    branch = branch[:branch.index(";;")]
    assert ".mod-new" not in branch, "the overwrite branch must not leave a .mod-new"
    assert "continue" in branch, "the overwrite branch must skip the compare path"
