"""Files the update overwrites must say so, and only those.

run-append.sh overwrites every ff-*.cfg on each flash without asking, and
printer.base.cfg rides along with the software component, which a flash
replaces wholesale. That is only fair to the user if the file itself says so
before they edit it -- the alternative is a change that vanishes on the next
update with one line in a log nobody reads.

moonraker.conf is the counter-case and is checked from the other side: it is
KEPT when edited, because there is no include-and-override seam for it and a
printer reached through a tuned trusted_clients block would lose that access.
It must NOT carry the banner, or the banner starts lying.

Adding a config to payload/klipper/config/ therefore forces a decision here,
which is the point.
"""
import os

import pytest

BANNER = "DO NOT EDIT THIS FILE"
OVERRIDE_HINT = "printer.cfg"

# Overwritten wholesale on every update -- must warn.
OWNED_PREFIXES = ("ff-",)
OWNED_EXACT = ("printer.base.cfg",)

# Preserved when the user has edited it -- must not warn.
PRESERVED = ("moonraker.conf",)


def config_files(cfgdir):
    return sorted(f for f in os.listdir(cfgdir) if f.endswith((".cfg", ".conf")))


def owned(name):
    return name.startswith(OWNED_PREFIXES) or name in OWNED_EXACT


@pytest.fixture(scope="session")
def shipped(root):
    """What patch.sh copies to the printer, by basename.

    Read from the payload rather than a built tree so this needs no package:
    bin/patch.sh:80 ships ff-*.cfg, :88 printer.base.cfg, :128 moonraker.conf.
    """
    cfgdir = os.path.join(root, "payload", "klipper", "config")
    names = [f for f in config_files(cfgdir)]
    return cfgdir, names


def test_every_mod_owned_config_warns_the_user(shipped):
    cfgdir, names = shipped
    missing = []
    for name in names:
        if not owned(name):
            continue
        text = open(os.path.join(cfgdir, name), encoding="utf-8").read()
        if BANNER not in text:
            missing.append(name)
    assert not missing, (
        "these are overwritten on every update but do not say so: %s"
        % ", ".join(missing))


def test_the_warning_points_somewhere_useful(shipped):
    """A warning with no alternative is just a scolding."""
    cfgdir, names = shipped
    for name in names:
        if not owned(name):
            continue
        text = open(os.path.join(cfgdir, name), encoding="utf-8").read()
        head = text[:text.index(BANNER) + 2000]
        assert OVERRIDE_HINT in head, (
            "%s warns but never names printer.cfg as the place to put changes"
            % name)


def test_the_banner_is_at_the_top(shipped):
    """Past the first screenful it is not a warning, it is trivia."""
    cfgdir, names = shipped
    late = []
    for name in names:
        if not owned(name):
            continue
        lines = open(os.path.join(cfgdir, name), encoding="utf-8").read().splitlines()
        where = next(i for i, l in enumerate(lines) if BANNER in l)
        if where > 6:
            late.append("%s (line %d)" % (name, where + 1))
    assert not late, "banner buried too far down: %s" % ", ".join(late)


def test_preserved_configs_do_not_claim_to_be_overwritten(shipped, root):
    """moonraker.conf keeps the .mod-new dance, so it must not warn."""
    for name in PRESERVED:
        for base in (os.path.join(root, "payload", "klipper", "config"),
                     os.path.join(root, "assets")):
            path = os.path.join(base, name)
            if os.path.isfile(path):
                text = open(path, encoding="utf-8").read()
                assert BANNER not in text, (
                    "%s is kept when edited, so it must not carry the "
                    "overwrite warning" % name)


def test_installer_actually_overwrites_what_the_banner_promises(root):
    """The banner is a claim about run-append.sh -- hold it to that.

    A banner that says "overwritten every update" while the installer still
    leaves a .mod-new is worse than no banner: the user trusts it, puts nothing
    in printer.cfg, and their edit quietly wins instead.
    """
    src = open(os.path.join(root, "payload", "run-append.sh"),
               encoding="utf-8").read()
    body = src[src.index("klipper + moonraker configs"):]
    assert "ff-*.cfg)" in body, (
        "run-append.sh no longer special-cases ff-*.cfg; either restore the "
        "overwrite or drop the banner from those files")
    # The overwrite branch must not fall through to the .mod-new path.
    branch = body[body.index("ff-*.cfg)"):]
    branch = branch[:branch.index(";;")]
    assert ".mod-new" not in branch, "the ff-*.cfg branch must not leave a .mod-new"
    assert "continue" in branch, "the ff-*.cfg branch must skip the compare path"
